// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqjybLKj5WOw7rhKsI0BBZB5nLo9PU66o',
    appId: '1:111770215758:android:2d13c4b4698d47d2a72a1f',
    messagingSenderId: '111770215758',
    projectId: 'yearflow-app',
    storageBucket: 'yearflow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-BEaVHT_ifuN35MgJZcv6HSVkL7Onvk',
    appId: '1:111770215758:ios:6ade478ec1ef4ebba72a1f',
    messagingSenderId: '111770215758',
    projectId: 'yearflow-app',
    storageBucket: 'yearflow-app.firebasestorage.app',
    androidClientId: '111770215758-8aqovht48k3i77ekfvrqllto1jhp0dia.apps.googleusercontent.com',
    iosClientId: '111770215758-occloc6p41fj6el5oegvikp036a8t283.apps.googleusercontent.com',
    iosBundleId: 'com.yearflow.yearFlow',
  );

}